version: '2'

services:
  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    expose:
      - 27017
    container_name: mongo
    network_mode: host
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761

  config-service:
    build: config-server/
    restart: always
    network_mode: "host"
    image: config-service
    hostname: localhost
    ports:
      - 8888:8888

  zuul-apigateway:
    build: zuul/
    depends_on:
      - config-service
      - eureka-server
      - movie-service
      - user-service
    restart: always
    network_mode: "host"

    hostname: localhost
    ports:
      - 8081:8081

  movie-service:
    build: movie-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 9090:9090
    depends_on:
      - config-service
      - eureka-server



  user-service:
    build: user-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 9098:9098
    depends_on:
      - config-service
      - eureka-server


